#+TITLE: Informatics basics
#+AUTHOR: Starovoytov Alexandr, Grechko Georgy
#+DATE: <2021-09-04 Sat 13:50>
#+latex_header: \usepackage[russian]{babel}
#+latex_header: \usepackage[T2A]{fontenc}
# #+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>


+ [[https://stewkk.github.io/infbasics/inf_basics.pdf][Лекция в pdf формате]]
+ Преподаватель
  - Коновалов Александр Владимирович
  - 89175404352
  - akonovalov@bmstu.ru
  - a.v.konovalov87@mail.ru
* лекция 1
** Основные понятия информатики
*** Данные
это представление фактов, понятий, инструкций в форме, приемлемой
для обмена, интерпретации или обработки человеком или с помощью
автоматических средств
*** Алгоритм
это конечная совокупность точно заданных правил решения прозвольного класса
задач или набор инструкций, описывающий порядок действий исполнителя для
решения некотрой задачи
*** Свойства алгоритма:
1. Дискретность - 
    делится на отдельные элементарные части, отвечающие за определенные действия.
2. Детерминированность - 
    на одних и тех же входных данных - один и тот же результат.
3. Понятность - 
    элементы алгоритма должны быть понятны исполнителю.
4. Завершаемость - 
    если не завершается - то это вычислительный процесс.
5. Массовость - 
    алгоритм пригоден для решения всех задач данного типа.
6. Результативность - 
    указывает на наличие таких исходных данных, для которых реализуемый
    по заданному алгоритму вычислительный процесс должен через конечное
    число шагов остановиться и выдать искомый результат.
*** Компьютерная программа
это алгоритм, записанный на некотором языке программирования
*** Язык программирования
формальный язык, предназначенный для записи компьютерных программ
*** Компьютер
программно управляемое устройство для обработки информации
*** Подпрограмма
некоторый именованный блок кода. \\
Вызывающая программа приостанавливается, управление передается
подпрограмме,
по завершению управление передается обратно
*** Сопрограмма
в отличие от подпрограммы работает поочередно с вызывающей программой.
При повторном вызове возобновит выполнение с момента, где остановилась
** Парадигмы программирования
совокупность идей и понятий, определяющих стиль написания компьютерных
программ (подход к программированию). Это способ концептуализации,
определяющий организацию вычислений и структурирование работы, выполняемой
компьютером.
*** Основные группы парадигм
1. Императивные
   способ записи программ, в котором указывается последовательность
   действий \\
   основной признак - оператор присваивания (меняющий значение переменной)
   1. Структурное программирование
      программа является композицией блоков с одним входом и
      одним выходом \\
      (есть операторы ветвления и цикла, но нет goto)
   2. Процедурное программирование
      совокупность подпрограмм, где одни подпрограммы вызывают другие
   3. Объектно-ориентированное
      программа рассматривается как набор некоторых взаимодействующих
      объектов. \\
      Объект сочетает в себе данные и методы их обработки,
      методы вызываются в ответ на сообщение: \\
      посылаем сообщение объекту -> вызывает метод -> возвращает ответ \\
      объекты объединяются в классы
2. Декларативные
   способ записи программ, в котором описывается взаимосвязь между
   данными, описывается цель, но не последовательность шагов ее вычисления
   1. Функциональное
      алгоритм записывается как набор взаимосвязанных функций, функции
      рассматриваются с математической точки зрения, \\
      описывает взаимосвязь между данными и результатом
      #+begin_src "c"
      x = f(y) + g(z);
      #+end_src
   2. Логическое (Prolog + отчасти SQL)
      алгоритм описывает взаимосвязь между понятиями. \\
      Выполнение программы сводится к выполнению запросов
3. Метапрограммирование
   метаирония. Программа рассматривается как данные/объект для
   другой программы
   1. Программу пишут программы
      Например: макросы, генераторы кода, шаблоны С++ (фигня нечитаемая
      зачем он постоянно в руках часы крутит попит симпл димпл круче
      нет попит симпл димпл попит симпл димпл маленький красивый
      попит большой и милый)
   2. Программа взаимодействует с вычислительной средой
      Рефлексия или интроспекция - самоанализ. \\
      Например, посмотреть поля и значения в объекте класса
*** примеры
#+begin_example
ИП: sort(array);
ФП: sorted_list = sort(list)
    sorted_list - константа, т.к. нет присваивания
ЛП: sort(unsorted, sorted)
#+end_example
** язык Scheme
*** информация о языке
Lisp 1950-е годы Джон МакКарти \\
LISt Processing \\
Scheme 1970-е годы Абельсон и Сассман \\
изучаем R5RS \\
современная редакция R7RS
- другие языки семейства LISP:
    - Common Lisp
    - Clojure
    - Racket
